//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingCD.Resources.View {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeddingCD.Resources.View.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        public static string Accueil {
            get {
                return ResourceManager.GetString("Accueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rua do Redolho 4620-503 Pias (Lousada).
        /// </summary>
        public static string AdresseQuinta {
            get {
                return ResourceManager.GetString("AdresseQuinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couple.
        /// </summary>
        public static string Couple {
            get {
                return ResourceManager.GetString("Couple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Galerie.
        /// </summary>
        public static string Galerie {
            get {
                return ResourceManager.GetString("Galerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Histoire.
        /// </summary>
        public static string Histoire {
            get {
                return ResourceManager.GetString("Histoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci à tous !.
        /// </summary>
        public static string Merci {
            get {
                return ResourceManager.GetString("Merci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nous nous sommes mariés !.
        /// </summary>
        public static string MessageAccueil {
            get {
                return ResourceManager.GetString("MessageAccueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Machado.
        /// </summary>
        public static string NomFemme {
            get {
                return ResourceManager.GetString("NomFemme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Da Costa Oliveira.
        /// </summary>
        public static string NomHomme {
            get {
                return ResourceManager.GetString("NomHomme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quinta Redolho de Cima.
        /// </summary>
        public static string NomQuinta {
            get {
                return ResourceManager.GetString("NomQuinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notre.
        /// </summary>
        public static string Notre {
            get {
                return ResourceManager.GetString("Notre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notre histoire.
        /// </summary>
        public static string NotreHistoire {
            get {
                return ResourceManager.GetString("NotreHistoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cécile.
        /// </summary>
        public static string PrenomFemme {
            get {
                return ResourceManager.GetString("PrenomFemme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diégo.
        /// </summary>
        public static string PrenomHomme {
            get {
                return ResourceManager.GetString("PrenomHomme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie.
        /// </summary>
        public static string Propriete_Category {
            get {
                return ResourceManager.GetString("Propriete_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Photo.
        /// </summary>
        public static string Propriete_PictureToUpload {
            get {
                return ResourceManager.GetString("Propriete_PictureToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mariage Cécile &amp; Diégo.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous.
        /// </summary>
        public static string Tous {
            get {
                return ResourceManager.GetString("Tous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ &quot;Catégorie&quot; est obligatoire..
        /// </summary>
        public static string Validation_Category_Required {
            get {
                return ResourceManager.GetString("Validation_Category_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ &quot;Photo&quot; est obligatoire..
        /// </summary>
        public static string Validation_PictureToUpload_Required {
            get {
                return ResourceManager.GetString("Validation_PictureToUpload_Required", resourceCulture);
            }
        }
    }
}
